---
version: "2.0"
services:
  benchmark-16gb:
    image: zjuuu/gpu-benchmark:0.10
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - FOLDER_NAME=
      - NAME_DATASET=all
      - NAME_CONFIG=16GB
      - NAME_MODEL=all
      - TIMEOUT=3000
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_BUCKET=
profiles:
  compute:
    benchmark-16gb:
      resources:
        cpu:
          units: 12
        memory:
          size: 32GB
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: t4
                - model: p100
                - model: a4000
  placement:
    dcloud:
      pricing:
        benchmark-16gb:
          denom: uakt
          amount: 1000
deployment:
  benchmark-16gb:
    dcloud:
      profile: benchmark-16gb
      count: 1
