---
version: "2.0"
services:
  benchmark-a100-80gb:
    image: zjuuu/gpu-benchmark:0.11
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - START=true
      - FOLDER_NAME=
      - NAME_DATASET=all
      - NAME_CONFIG=A100_80GB_SXM4_v1
      - NAME_MODEL=all
      - TIMEOUT=3000
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_BUCKET=
profiles:
  compute:
    benchmark-a100-80gb:
      resources:
        cpu:
          units: 12
        memory:
          size: 32GB
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100-80
  placement:
    dcloud:
      pricing:
        benchmark-a100-80gb:
          denom: uakt
          amount: 1000
deployment:
  benchmark-a100-80gb:
    dcloud:
      profile: benchmark-a100-80gb
      count: 1
