---
version: "2.0"
services:
  benchmark-rtx8000:
    image: zjuuu/gpu-benchmark:0.9
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      #- "CONFIG_URL=https://raw.githubusercontent.com/zJuuu/akash-benchmark-config/main/FoundryStaking/config_pytorch_FS_QuadroRTX8000_v1.sh"
      - NAME_DATASET=all
      - NAME_CONFIG=QuadroRTX8000_v1
      - NAME_MODEL=all
      - TIMEOUT=3000
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_BUCKET=
profiles:
  compute:
    benchmark-rtx8000:
      resources:
        cpu:
          units: 12
        memory:
          size: 32GB
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx8000
  placement:
    dcloud:
      pricing:
        benchmark-rtx8000:
          denom: uakt
          amount: 1000
deployment:
  benchmark-rtx8000:
    dcloud:
      profile: benchmark-rtx8000
      count: 1
