---
version: "2.0"
services:
  benchmark-v100:
    image: zjuuu/gpu-benchmark:0.10
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    env:
      - "CONFIG_URL=https://raw.githubusercontent.com/zJuuu/akash-benchmark-config/main/configs/config_pytorch_V100_32GB.sh"
      - FOLDER_NAME=
      - NAME_DATASET=all
      - NAME_MODEL=all
      - TIMEOUT=3000
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_BUCKET=
profiles:
  compute:
    benchmark-v100:
      resources:
        cpu:
          units: 12
        memory:
          size: 32GB
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: v100
  placement:
    dcloud:
      pricing:
        benchmark-v100:
          denom: uakt
          amount: 1000
deployment:
  benchmark-v100:
    dcloud:
      profile: benchmark-v100
      count: 1
